#!/bin/bash

myprogramfiles="create_axis.f90 Gauss_Seidel_solver.f90 command_line.f90"


outfile="solve"


fc=gfortran

echo "Compiling $outfile"

$fc -g -std=f2008 $myprogramfiles -o $outfile

if [[ $? -ne 0 ]]; then
    echo "Error: Compilation of $outfile failed. Exiting."
    exit 1
fi


echo "Compilation of $outfile successful."


echo "Executing $outfile"


./$outfile nx=11 ny=11 problem=single

if [[ $? -ne 0 ]]; then
    echo "Error: Execution of $outfile failed. Exiting."
    exit 1
fi

echo "Execution of $outfile successful."