#!/bin/bash

myprogramfiles="create_axis.f90 Gauss_Seidel_solver.f90 command_line.f90 main.f90 Verlet.f90 netCDF_writer.f90"


outfile="trajectory_solver"

fflags=`nf-config --fflags`
flibs=`nf-config --flibs`



fc=gfortran

echo "Compiling $outfile"

$fc -g $fflags -std=f2008 $myprogramfiles  $flibs -o $outfile

if [[ $? -ne 0 ]]; then
    echo "Error: Compilation of $outfile failed. Exiting."
    exit 1
fi


echo "Compilation of $outfile successful."


echo "Executing $outfile"


./$outfile nx=100 ny=100 problem=double

if [[ $? -ne 0 ]]; then
    echo "Error: Execution of $outfile failed. Exiting."
    exit 1
fi

echo "Execution of $outfile successful."

plotfile="TrajectoryPlotter.py"

echo "Executing $plotfile"

python3 $plotfile


if [[ $? -ne 0 ]]; then
    echo "Error: Execution of $plotfile failed. Exiting."
    exit 1
fi



echo "Execution of $plotfile successful."
echo "All tasks completed successfully."


plot1="E_x.jpg"
plot2="Trajectory.jpg"

code $plot1

code $plot2
